server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server7001
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: eureka7001.com
    prefer-ip-address: true
  client:
    # false表示不向服务中心注册自己
    register-with-eureka: false
    # fetch表示从服务中心获取服务，因为自身就是服务中心，因此不需要获取
    fetch-registry: false
    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka